#!/usr/bin/env python3
"""Convert the diff/ and diff_mod/ full-file overlays into reviewable patches.

For every file in an overlay, emits one git-apply-able .patch (unified diff
against the pristine baseline) under patches/, mirroring the relative path:

    patches/money/             <- diff/     vs build/orig/  (wc4_ru variant)
    patches/money_and_assets/  <- diff_mod/ vs decompiled/  (wc4_ru_mod variant)

Prerequisite (creates the baselines and refreshes both overlays):

    cmake --preset default
    cmake --build build --target decompile
    cmake --build build --target sync

Then regenerate patches/ from scratch:

    python3 migrate.py
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

repo_root = Path(__file__).resolve().parent
patches_dir = repo_root / "patches"

# (patch group, overlay with full files, pristine baseline to diff against)
jobs = [
    ("money", "diff", "build/orig"),
    ("money_and_assets", "diff_mod", "decompiled"),
]


def git_diff(old: Path | None, new: Path) -> str:
    """Unified git diff old -> new ('old=None' means the file is new).

    Returns an empty string when both files are identical.
    """
    cmd = ["git", "diff", "--no-index", "--binary", "--"]
    cmd.append(os.devnull if old is None else str(old))
    cmd.append(str(new))
    proc = subprocess.run(
        cmd,
        cwd=repo_root,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="surrogateescape",
    )
    if proc.returncode == 0:
        return ""
    if proc.returncode != 1:
        raise RuntimeError(f"git diff failed for '{new}':\n{proc.stderr}")
    return proc.stdout


def rebase_paths(patch: str, rel: str, is_new: bool) -> str:
    """Point patch headers at a/<rel> / b/<rel> so `git apply -p1` works.

    Only the header block is rewritten; hunk bodies may legitimately contain
    lines starting with '--- ' (a removed '-- ...' line), so rewriting stops
    after the '+++ ' line.
    """
    out = []
    in_header = True
    for line in patch.splitlines(keepends=True):
        if in_header and line.startswith("diff --git "):
            line = f"diff --git a/{rel} b/{rel}\n"
        elif in_header and line.startswith("--- "):
            line = "--- /dev/null\n" if is_new else f"--- a/{rel}\n"
        elif in_header and line.startswith("+++ "):
            line = f"+++ b/{rel}\n"
            in_header = False
        out.append(line)
    return "".join(out)


def migrate(group: str, overlay: Path, baseline: Path) -> int:
    """Diff every overlay file against the baseline; return patch count."""
    count = 0
    for src in sorted(overlay.rglob("*")):
        if not src.is_file():
            continue
        rel = src.relative_to(overlay).as_posix()
        old = baseline / rel
        patch = git_diff(old if old.exists() else None, src)
        if not patch:
            print(f"warning: no changes, skipped: {overlay.name}/{rel}")
            continue
        out = patches_dir / group / f"{rel}.patch"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(
            rebase_paths(patch, rel, is_new=not old.exists()),
            encoding="utf-8",
            errors="surrogateescape",
        )
        print(f"  {group}/{rel}.patch")
        count += 1
    return count


def write_readme(counts: dict[str, int]) -> None:
    lines = [
        "# patches/",
        "",
        "Generated by `migrate.py` — do not edit by hand, regenerate:",
        "",
        "```bash",
        "cmake --preset default",
        "cmake --build build --target decompile",
        "cmake --build build --target sync",
        "python3 migrate.py",
        "```",
        "",
        "| group | overlay | baseline | apk variant | patches |",
        "|---|---|---|---|---|",
        f"| `money/` | `diff/` | `build/orig/` | `wc4_ru` | {counts['money']} |",
        f"| `money_and_assets/` | `diff_mod/` | `decompiled/` | `wc4_ru_mod` | {counts['money_and_assets']} |",
        "",
        "`money/` = 5play money-mod base + Russian translation + 5play debloat.",
        "`money_and_assets/` = `money/` + game-data hacks (unlocks, damage, ...).",
        "",
        "## Apply",
        "",
        "```bash",
        "# money/ applies onto a pristine decompile:",
        "find patches/money -name '*.patch' -exec git -C build/orig apply \"$PWD/{}\" \\;",
        "",
        "# money_and_assets/ applies on top of the ru tree:",
        "find patches/money_and_assets -name '*.patch' -exec git -C decompiled apply \"$PWD/{}\" \\;",
        "```",
        "",
    ]
    (patches_dir / "readme.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    for group, overlay, baseline in jobs:
        if not (repo_root / overlay).is_dir():
            print(
                f"error: '{overlay}/' not found — run from the repo root",
                file=sys.stderr,
            )
            return 1
        if not (repo_root / baseline).is_dir():
            print(
                f"error: baseline '{baseline}/' not found for '{group}'\n"
                "  fix: cmake --preset default"
                " && cmake --build build --target sync",
                file=sys.stderr,
            )
            return 1

    if patches_dir.exists():
        shutil.rmtree(patches_dir)
    patches_dir.mkdir()

    counts = {}
    for group, overlay, baseline in jobs:
        print(f"{group}: {overlay}/ vs {baseline}/")
        counts[group] = migrate(group, repo_root / overlay, repo_root / baseline)

    write_readme(counts)
    print(f"\ndone => 'patches/' ({sum(counts.values())} patches + readme.md)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
