cpmaddpackage(
    NAME
    fastgltf
    GITHUB_REPOSITORY
    spnda/fastgltf
    GIT_TAG
    v0.9.0
    SYSTEM
    ON
    EXCLUDE_FROM_ALL
    ON
    GIT_SHALLOW
    ON
    OPTIONS
    "FASTGLTF_ENABLE_TESTS OFF"
    "FASTGLTF_ENABLE_EXAMPLES OFF"
    "FASTGLTF_ENABLE_DOCS OFF"
    "FASTGLTF_ENABLE_GLTF_RS OFF"
    "FASTGLTF_ENABLE_ASSIMP OFF"
    "FASTGLTF_USE_CUSTOM_SMALLVECTOR OFF"
    "FASTGLTF_DISABLE_CUSTOM_MEMORY_POOL OFF")
