name: ci

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/logo.png'
      - '.github/logo.svg'
      - '.github/dependabot.yml'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/logo.png'
      - '.github/logo.svg'
      - '.github/dependabot.yml'
      - '.github/ISSUE_TEMPLATE/**'

permissions:
  contents: read
  packages: read

jobs:
  localized:
    uses: ./.github/workflows/build.yml
    with:
      variant: localized
    secrets: inherit

  money:
    uses: ./.github/workflows/build.yml
    with:
      variant: money
    secrets: inherit

  unlock_all:
    uses: ./.github/workflows/build.yml
    with:
      variant: unlock_all
    secrets: inherit
